### PR TITLE
Email fixes & env cleanup

### LINKED ISSUE #6: Bug when making new users using command on install. new users get an email on creation, when setting up the panel the email details are most likely not added yet so this throws and error

### PR DESCRIPTION
**Pull request by AGuyNamedJens**
Currently includes:

~- Adds a SetupMail console command, makes setting email into the database easier (Should add a test mail function?) #6~
~- Adds a function to CreateUser console command when it's run again, it will delete the old user from the database, since if e-mail fails, the user doesn't get admin permissions (Should just rewrite the whole thing I guess)~
~- Adds a check to the notification method to not send anything if password is `null`~
~- Temp fix for crashing e-mail bug, should fix #6 but would make it unclear for people why their e-mail doesn't work. Improve this 💯~

Above features have changed according to the reviews

- Adds a new boolean "enabled" on the Mail settings
- Adds a check on registered users so mails don't send by default and mails don't send if mailing isn't enabled
- Added new email enabled field
- Cleaned up the .ENV file

Changes will be made, hence why it's a draft PR

### CODE REVIEW

**Comment by AGuyNamedJens** [comment]
Alright so I spoke to Laravel experienced people, they mentioned that with how the email check is inside of "User Created" event, it's literally impossible to fix #6. which means we'll have to tell them to use a proper email service before doing anything on the panel unless we change the email method to be outside of the created event @AVMG20

File: app/Console/Commands/Setup/SetupCreateUserCommand.php [hunk 1]
```diff
@@ -71,6 +71,20 @@ public function handle()
             return 0;
         }
 
+        // Check if the user exists in the database
+        if(User::where('pterodactyl_id', $ptero_id)->exists()) {
```
Comment (AVMG20) [inline app/Console/Commands/Setup/SetupCreateUserCommand.php]: why? this command is used to make the initial user. not to keep on making users

File: app/Console/Commands/Setup/SetupMailCommand.php [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+        $this->client = $client;
+        $this->settings = $settings;
+    }
+
+    /**
+     * Execute the console command.
+     *
+     * @return int
+     */
+    public function handle()
```
Comment (AVMG20) [inline app/Console/Commands/Setup/SetupMailCommand.php]: i personally think having a command to set-up email details is not nesseary since you can do this once you are logged in in the back-end which is guided by a UI and validations. plus test button. which is i think more user friendly so a command would be pretty double.

File: app/Observers/UserObserver.php [hunk 3]
```diff
@@ -22,8 +25,19 @@ public function created(User $user)
             ->where('name', '=' , 'welcome-message')
             ->firstOrFail();
 
-        if (!$notificationTemplate->disabled) {
-            $user->notify($notificationTemplate->getDynamicNotification(compact('user')));
+        if (!$notificationTemplate->disabled && app(MailSettings::class)->mail_password !== null) {
```
Comment (AVMG20) [inline app/Observers/UserObserver.php]: like i mentioned earlier, i would like the MailSettings be added to the constructor instead of calling app directly.

File: app/Console/Commands/Setup/SetupCreateUserCommand.php (hunk 1 above)
Comment (AGuyNamedJens) [reply app/Console/Commands/Setup/SetupCreateUserCommand.php]: It's to check if the current user exists, it was a check to let the user be recreated during my testing stage, used for when the admin assignment fails due to email authentication not being set-up

File: app/Console/Commands/Setup/SetupMailCommand.php (hunk 2 above)
Comment (AGuyNamedJens) [reply app/Console/Commands/Setup/SetupMailCommand.php]: So no set-up command, but then how can you login if the original user gets a welcome message? Should I remove the whole welcome email function?

File: app/Observers/UserObserver.php [hunk 4]
```diff
@@ -22,8 +25,19 @@ public function created(User $user)
...
+            try {
+                $user->notify($notificationTemplate->getDynamicNotification(compact('user')));
+            } catch (\Exception $e) {
+                // log the error to laravel logs
+                Log::error($e->getMessage());
+
+                if(app()->runningInConsole()) {
+                    $out = new ConsoleOutput();
```
Comment (AVMG20) [inline app/Observers/UserObserver.php]: There is no console output when this is triggered by a job or user action. If this, for some reason, fails, it should never fail. It should just error out, which adds logs to the log files

Comment (AVMG20) [reply app/Observers/UserObserver.php]: i would rather see the error catching for console output in the command instead. not add all kinds of error handeling in the method that is not ment to handle this. but in my opion you can leave the handeling out like mentioned above.

Comment (AGuyNamedJens) [reply app/Observers/UserObserver.php]: It was also used for debug purposes, because when the email fails it threw the error and basically said goodbye and good luck to the user, thought this would make it clear for e-mail failures when used from the console: 
image

**Comment by AGuyNamedJens** [comment]
@AVMG20 If you merge this one (or the other PRs) let me know so i can update this PR to match those

**Review by AVMG20 — APPROVED** [review]
